@URL = http://localhost:3001/api/persons

### Get all
GET {{URL}}

### Get
GET {{URL}}/65004439dd9070a486c71700

### Add
POST {{URL}}
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "040-1231236"
}

### Delete
DELETE {{URL}}/65009b812d0fb84311eff260
